package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.OrderDO;

public interface OrderDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 07 17:03:58 CST 2023
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 07 17:03:58 CST 2023
     */
    int insert(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 07 17:03:58 CST 2023
     */
    int insertSelective(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 07 17:03:58 CST 2023
     */
    OrderDO selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 07 17:03:58 CST 2023
     */
    int updateByPrimaryKeySelective(OrderDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_info
     *
     * @mbg.generated Fri Jul 07 17:03:58 CST 2023
     */
    int updateByPrimaryKey(OrderDO row);
}