package com.miaoshaproject.dao;

import com.miaoshaproject.dataobject.SequenceDO;

public interface SequenceDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 07 21:43:29 CST 2023
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 07 21:43:29 CST 2023
     */
    int insert(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 07 21:43:29 CST 2023
     */
    int insertSelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 07 21:43:29 CST 2023
     */
    SequenceDO selectByPrimaryKey(String name);
    SequenceDO  getSequenceByName(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 07 21:43:29 CST 2023
     */
    int updateByPrimaryKeySelective(SequenceDO row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sequence_info
     *
     * @mbg.generated Fri Jul 07 21:43:29 CST 2023
     */
    int updateByPrimaryKey(SequenceDO row);
}